export const departments = [
  "DPR",
  "DESIGN CHECKING",
  "DOCUMENT",
  "MONITORING",
  "MONITORING WORKS",
  "WORKS",
  "LOCO TRIALS",
  "SITE WORK IMAGES",
  "TELECOM RECORDS",
  "CIVIL",
  "TAG PLACEMENT PLANS",
  "ACCOUNTS",
];
